name: severnaya_korzina
description: Платформа коллективных закупок для Усть-Неры

version: 4.3.5+34  # ВАЖНО: обновлять при каждом релизе!

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # HTTP запросы
  http: ^1.2.0
  
  # State management
  provider: ^6.1.1
  
  # Локальное хранение
  shared_preferences: ^2.3.0
  sqflite: ^2.3.2
  path: ^1.9.0
  
  # Форматирование даты
  intl: ^0.20.0
  mask_text_input_formatter: ^2.9.0
  json_annotation: ^4.9.0
  qr_flutter: ^4.1.0
  
  # URL Launcher для открытия ссылок
  url_launcher: ^6.2.0
  
  # WebView ТОЛЬКО базовый пакет, БЕЗ webview_flutter_web!
  webview_flutter: ^4.5.0
  # webview_flutter_web: ^0.2.2+4  # ❌ УДАЛИТЬ ЭТУ СТРОКУ!
  
  # SMS отправка
  dio: ^5.4.0
  
  # Безопасное хранение
  flutter_secure_storage: ^9.2.1
  
  # Утилиты
  uuid: ^4.3.0
  
  # Валидация
  validators: ^3.0.0

  # === НОВЫЕ ЗАВИСИМОСТИ ДЛЯ ОБНОВЛЕНИЙ ===
  package_info_plus: ^8.3.1      # Получение информации о версии приложения
  open_file: ^3.5.10               # Открытие APK файла для установки
  permission_handler: ^12.0.1     # Управление разрешениями
  path_provider: ^2.1.5           # Работа с путями файловой системы

dev_dependencies:
  flutter_launcher_icons: ^0.14.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  flutter_native_splash: ^2.3.10

flutter:
  uses-material-design: true
  # Добавьте эту секцию для шрифтов
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
  
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_iconn.png"
  min_sdk_android: 21
  
  adaptive_icon_background: "#2196F3"  # Синий цвет как у вашего бренда
  # android_adaptive_icon_foreground: "assets/icons/app_icon_foreground.png"
  
  remove_alpha_ios: true
  
  # Настройки для веб убираем, так как это мобильное приложение
# web:
#   generate: true
#   image_path: "assets/icons/app_icon.png"