name: severnaya_korzina
description: Платформа коллективных закупок для Усть-Неры

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # HTTP запросы
  http: ^1.1.0
  
  # State management
  provider: ^6.0.5
  
  # Локальное хранение
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  path: ^1.8.3
  
  # Форматирование даты
  intl: ^0.18.1
  mask_text_input_formatter: ^2.9.0
  json_annotation: ^4.9.0
  qr_flutter: ^4.1.0
  url_launcher: ^6.3.2
  # НОВАЯ ЗАВИСИМОСТЬ для WebView:
  webview_flutter: ^4.4.2
  webview_flutter_web: ^0.2.2+4

 # SMS отправка
  dio: ^5.4.0  # Для HTTP запросов к SMS API

  # Безопасное хранение
  flutter_secure_storage: ^9.0.0

  # Утилиты
  uuid: ^4.2.1
  
  # Валидация
  validators: ^3.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21
  
  # Дополнительные настройки для Android
  android_adaptive_icon_background: "#FFFFFF"
  android_adaptive_icon_foreground: "assets/icons/app_icon_foreground.png"
  
  # Настройки для iOS
  remove_alpha_ios: true
  
  # Для веб-версии
  web:
    generate: true
    image_path: "assets/icons/app_icon.png"
    background_color: "#FFFFFF"
    theme_color: "#2196F3"